GT=[];
odir_prefix      =   ['trkRVQE_AVSS2007_' num2str(Nict)];
GT{1}               =   csvread('GTBB_AVSS2007_360x288_redCar.txt'); %ground truth data
%GT{2}               =   csvread('GTBB_AVSS2007_360x288_blueCar.txt'); %ground truth data
bGTisComplete       =   false;      %there is complete ground truth information
F                   =   100;       %F is number of frames
f1I                 =   3190;        %initial frame when this target appears
f1F                 =   4000;        %final frame when this target leaves

dir_img             =   'img/AVSS2007_360x288/';                            %image directory
Iw                  =   360;
Ih                  =   288;  
sw                  =   21;  %RVQ parameters
sh                  =   31;      
Nsx                 =   3;
Nsy                 =   3;
M                   =   2;
T                   =   8;
gamma_STG           =   T;              %gammaolds
gamma_SNR           =   0.8*255;            
fI                  =   3190;           %current frame, initialize to where you want to train your snippets, next frame is tracking frame
tgtID               =   1;              %target ID
vx(tgtID)           =   3;              %target velocity
vy(tgtID)           =   1;              %"
Ww                  =   9;             %search window
Wh                  =   5;             %"
cfn_img             =   [dir_img num2str(fI) '.png'];     
lambda              =   0.5;
